services:
  # Sevice of the data base PostgreSQL
  db:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: iam_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # Service with backend (API with Python)
  backend:
    container_name: iam_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .logs:/app/logs
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db 

  #Service Frontend (React)
  frontend:
    container_name: iam_frontend
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: